### ISSUE TITLE
Consul does not support /global at all

### ISSUE THREAD

**Issue by EugenMayer** [markround/tiller#32] opened 2016-06-29 11:41 UTC
neither global/all nor global/$ENV are used when working with templates. I created a docker image for this testcase

```
docker run --rm -e TILLER_ENV=production eugenmayer/tiller-test:consul
```

This does work, since values are fetched from tiller/values/production/test.erb/should_be_overriden
so the template based values.

Using env development, since i did not set a template value there,

```
docker run --rm -e TILLER_ENV=development eugenmayer/tiller-test:consul
```

it does neither pick up 
- tiller/globals/development/should_be_overriden

nor it picks up
-  globals/all/should_be_overriden

it simply uses "defaults". You can check how to setup does look like here

Tiller config
 - https://github.com/EugenMayer/tiller-test/blob/master/consul/build/tiller/common.yaml
 
Consul-Population:
 - https://github.com/EugenMayer/tiller-test/blob/master/consul/build/bootstrap.sh#L11

You see that i do not push a template-based value for development, only production, to work out the edge case

**So summarized, the issue is:**
neither no value out of tiller/globals is picked up, not all not env specific
values/$env/$template works though

**Comment by EugenMayer** [comment] 2016-07-01 10:38
It would be so great if you could work on this one since its a huge blocker!thanks

**Comment by markround** [comment] 2016-07-01 12:44
Hi, I should get a chance to work through the backlog over the next week. I'll make sure this is the first issue I tackle.

**Comment by EugenMayer** [comment] 2016-07-01 15:47
Thank you!

**Comment by markround** [comment] 2016-07-11 11:50
Right. Having taken a quick look at this, I think I see what is going on. The issue you're running into is a combination of behaviours:

1. Variables defined in the context of a template (e.g. your `should_be_overriden` in your production environment) will always take precedence over global values. 
2. In your defaults section, when you define `should_be_overriden: 'global'`, this is created as a template-specific variable, and will therefore also take precedence over a global variable with the same name.
3. In your development environment, you don't specify a block for `test.erb`, and as there are no valid blocks for that template in consul, it falls back on using the defaults data-source. This then ignores the global `should_be_overridden` value for that environment as the template-specific value from the defaults block takes precedence.

As such, it looks like it's not a bug as such, rather a combination of behaviours perhaps not working as you'd expect them to. The global-vs-template vars issue is documented in the "Gotchas" section of the README.md, but if you think it could be clearer, I'm open to suggestions.

If you let me know what you're trying to achieve, perhaps I can craft a config for you that will do what you want ?

**Comment by EugenMayer** [comment] 2016-07-14 18:46
Well it is really getting confusing how you see global values and environments.

I define defaults for a template in a environment-unspecific section, so super global, super generic.

Then i push global values into a environment, which should overlay anything super-global. Since globals do get picked up when nothing is defined for a template, i would have expected that a global value in an env is picked up, if no specific template config value is configured in this env.

Global is seen as "for all templates" not "for no templates". E.g an PHP error level, lets say you render several templates. Each template might have its own, defined in the defaults section globals, but for dev, you want set global error_level=X for all templates.

**Comment by markround** [comment] 2016-07-15 09:37
I guess I'm still not understading you 100%, sorry :( Probably me being bad at explaining this...

Apologies in advance for this wall of text, but I just wanted to make sure we're both on the same page. If you find any of this useful, I'll copy & paste it into the docs somewhere.

So - just to clarify, a global var applies to everything, but can be over-ridden by a environment-specific global var, and the highest priority is given to a var defined for a template; either in an environment block, or in a defaults section for a template.

global var > environment global var > template-specific var

If you have multiple definitions of the same var across different data sources, the data-source loaded last will take priority. Or, to put it more simply:

*A template var* ***always*** *over-rides a global var, and can only be over-ridden by another template var from a higher priority plugin*.

With these two behaviours, if you have a defaults section which includes template-specific values like the one in your example `common.yaml`, then the globals will never get used, no matter what order you load things in. This is because a template-specific var will *always* over-ride a global var.

The defaults module was originally intended to allow only generic global vars to be defined for environments, but was extended to allow you to specify full template definitions in case there was a template that would be *identical* in all environments - this would save you from having multiple definitions for the same template across all your environments.

Of course, by using the the plugin load order, you can over-ride it later with another template-specific var:

common.yaml:
```yaml
---
exec: ["true"]
data_sources: [ "defaults" , "file" ]
template_sources: [ "file" ]

defaults:
  test.erb:
    config:
      test_var: "This is from defaults"

environments:
  development:
    test.erb:
      target: test.txt
      config:
        test_var: "This is from the environment block"
```

templates/test.erb:
```erb
var : <%= test_var %>
```

Running it :
```
$ ./bin/tiller -b ./t -n -v                                                                                                                               
tiller v0.7.9 (https://github.com/markround/tiller) <github@markround.com>
Using common.yaml v2 format configuration file
Using configuration from ./t
Using plugins from /usr/local/lib/tiller
Using environment development
Template sources loaded [FileTemplateSource]
Data sources loaded [DefaultsDataSource, FileDataSource]
Available templates : ["test.erb"]
Warning, merging duplicate data values.
test_var => 'This is from defaults' being replaced by : 'This is from the environment block' from FileDataSource
Building template test.erb
Not running as root, so not setting ownership/permissions on test.txt
Template generation completed

$ cat test.txt
var : This is from the environment block
```

If we swap the load order around ( `data_sources: [ "file" , "defaults" ]`) - not sure why you'd ever want to do this, but it demonstrates the point:

```
$ ./bin/tiller -b ./t -n -v                                                                                                                               
...
...test_var => 'This is from the environment block' being replaced by : 'This is from defaults' from DefaultsDataSource
...

$ cat test.txt
var : This is from defaults
```

To add another data-source into the mix, if I add Consul with an environment-specific `test_var`, and a template-specific `test_var`, with the following load order:

`data_sources: [ "consul" , "defaults" , "file" ]`

You see the following behaviour:

```
test_var => 'This is the Consul value for the development environment' being replaced by : 'This is the Consul template var' from ConsulDataSource
Warning, merging duplicate data values.
test_var => 'This is the Consul template var' being replaced by : 'This is from defaults' from DefaultsDataSource
Warning, merging duplicate data values.
test_var => 'This is from defaults' being replaced by : 'This is from the environment block' from FileDataSource
```

So, Consul is loaded first. The template-specific var over-rides the global for the development environment. Then, the defaults plugin gets used, and it over-rides the value from Consul. Finally, the file plugin gets used and this has the "final say".

Swapping the load-order round to `data_sources: [ "defaults" , "consul" , "file" ]` results in some different behaviour:

common.yaml:
```yaml
---
exec: ["true"]
data_sources: [ "defaults" , "consul" , "file" ]
template_sources: [ "file" ]

consul:
  url: "http://127.0.0.1:8500"
  register_services: true
  register_nodes: true

defaults:
  test_var: "This is a global from defaults"
  test.erb:
    config:
      test_var: "This is a template var from defaults"


environments:
  development:
    test.erb:
      target: test.txt
      config:
        test_var: "This is from the environment block"

```

This gives us (referenced below):

```
(1) - no output

(2) test_var => 'This is the Consul value for the development environment' being replaced by : 'This is a template var from defaults' from DefaultsDataSource

(3) test_var => 'This is a template var from defaults' being replaced by : 'This is the Consul template var' from ConsulDataSource

(4) test_var => 'This is the Consul template var' being replaced by : 'This is from the environment block' from FileDataSource
```

Which at first may look strange - we loaded defaults first, but it's replacing something from consul which is loaded afterwards. But, this is where the variable precedence takes effect. So, stepping through this:

1. Defaults module gets loaded. `test_var` is defined as a template-specific var so that's the value that will be used for that `test.erb` template (at this point, another template will still get the global value from defaults). No warning output is generated at this point, but I'll look at adding that in so it's clear what's happening.
2. Consul plugin gets loaded. We then have a Consul global value being over-ridden by a template var from defaults - even though Defaults was loaded first, *remember a template var always over-rides a global var, and can only be over-ridden by another template var from a higher priority plugin*.
3. So, next we have a Consul template var replacing the template var from the defaults module. This is expected, as the consul plugin was loaded after the defaults plugin, so has a higher priority.
4. Finally, the template var from the file module replaces everything as that was the last plugin to be loaded.

Does this make sense ?

**Comment by markround** [comment] 2016-08-01 12:35
Closing this issue as I think this is down to a mis-understanding of Tiller's behaviour. I've updated the docs to hopefully make this clearer. Please re-open if you believe this to be a genuine bug.

**Closed by markround** 2016-08-01 12:35 UTC
