### ISSUE TITLE
Plans to support environment variables in "target" of environments/*.yaml files

### ISSUE THREAD

**Issue by gayetri** [markround/tiller#44] opened 2017-01-07 00:19 UTC
Hi,
I have a typical situation where I need to create a template for a log4j property file and I need to copy that file into a directory - which itself should be configurable via environment variables for a docker container.
However I noticed that in Tiller - I have to "hardcode" the target - kind of like - lets say I have a yaml file for the development environment wherein my development.yaml file looks like:

log4j-properties_template.erb:
  target: /usr/share/spark/conf

"/usr/share/spark/conf" is a directory that I want to configure using environment variables.
How can I accomplish this? Am I missing something or is this feature not available in Tiller.

Any help will be appreciated.

**Comment by markround** [comment] 2017-02-06 11:17
Duplicate of #47 which is now in progress and currently merged to /develop branch, so will be in the next release of Tiller (probably v1.0.0 as I'm switching to semantic versioning)

**Closed by markround** 2017-02-06 11:17 UTC
Labels: duplicate

**Comment by markround** [comment] 2017-02-06 11:20
This test feature shows how you'd do this:

https://github.com/markround/tiller/blob/feature/dynamic_config/features/dynamic_values.feature#L103-L133

**Comment by gayetri** [comment] 2017-02-08 15:53
Thank you! Will try it out.
