### ISSUE TITLE
"File" DataSource is mandatory, or no templates will be rendered

### ISSUE THREAD

**Issue by EugenMayer** [markround/tiller#25] opened 2016-06-23 22:51 UTC
Reproduction:
Use your fixture https://github.com/markround/tiller/tree/master/features/fixtures/single_file and remove https://github.com/markround/tiller/blob/master/features/fixtures/single_file/common.yaml#L2 file here, since it should not be needed for this example - this example will no longer generate any templates.

like @ppl i mentioning in #24 its bailing out on https://github.com/markround/tiller/blob/master/bin/tiller#L133 so no target values could be read.

In my case i could get it working by simply adding : https://goo.gl/zRqxPf to my configuration made it work.

Either i really got data-sources wrong, or this is a bug. Thanks!

**Comment by markround** [comment] 2016-07-12 15:27
Hi, I'm closing this as I assume it's a duplicate of issue #24 - you need the file datasource to read in data from common.yaml or other files. I've updated the docs and pointed out that you most likely need the file plugin enabled for most uses, so I'm closing this as a documentation issue. Please re-open if I've misunderstood! Thanks again :)

**Closed by markround** 2016-07-12 15:27 UTC

**Comment by EugenMayer** [comment] 2016-07-12 16:26
makes sense to close this one, thanks!
