### ISSUE TITLE
Support exec-overrides in templates

### ISSUE THREAD

**Issue by EugenMayer** [markround/tiller#31] opened 2016-06-29 09:24 UTC
Since every template could have a different service it configures, i could be very handy and make a lot of sense, to be able to override the global exec.

Running several tiller-bases in this case is pretty much overhead and needs a lot more then this - i think this is also fairly simple to implement

What do you think?

**Comment by markround** [comment] 2017-02-06 12:02
Duplicate of #46

**Closed by markround** 2017-02-06 12:02 UTC
